
name: 'dbt_learn'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  dbt_project_evaluator:
    +schema: project_evaluator
  dbt_learn:
    seeds:
      +schema: seeds

models:
  dbt_project_evaluator:
    +schema: project_evaluator
  dbt_learn:
    staging:
      +schema: stg
      +materialized: view
    intermediate:
      +schema: int
      +materialized: table
    marts:
      +schema: mrt
      +materialized: table
